name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Good to go
      if: hashFiles('README.md')
      run: echo OK
    - name: I am documentation
      if: hashFiles('README.md') == false
      run: echo README
